from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='home'),

    path('snippets',views.snippets_home,name='snippets'),
    path('snippets/python/BlindSqlEnum',views.BlindSqlEnum,name='BlindSqlEnum'),
    path('snippets/linux/curl_json',views.curl_json,name='curl_json'),

    path('CVE',views.cve_home,name='cve'),
    path('CVE/laravel-cve-2021-3129',views.laravel_cve_2021_3129,name='laravel-cve-2021-3129'),
    path('CVE/Strapi-cve-2019-19609',views.Strapi_cve_2019_19609,name='Strapi-cve-2019-19609'),
    path('CVE/git-repo-cve-2022-24439',views.git_repo_CVE_2022_24439,name='git-repo-cve-2022-24439'),
    path('CVE/drupal_cve_2018_7600',views.drupal_cve_2018_7600,name='drupal_cve_2018_7600'),
    path('CVE/dirty_socket', views.dirty_socket,name='dirty_socket'),
    path('CVE/image_magick',views.image_magick,name='imagemagick'),
    path('CVE/js2py',views.js2py,name='js2py'),
    path('CVE/npbackup_cli',views.npbackup_cli,name='npbackup_cli'),

    path('jargons', views.jargons,name='jargons'),
    path('jargons/internet',views.internet,name='internet'),
    path('jargons/ActiveDirectory',views.ad,name='ad'),


    path('Phishing', views.phishing,name='phishing'),
    path('Vanish',views.vanish,name='vanish'),

    path('vulnerabilities', views.vulnerabilities,name='vulnerabilities'),
    path('vulnerabilities/SSTI',views.ssti,name='SSTI'),
    path('vulnerabilities/SQLi',views.sqli,name='SQLi'),
    path('vulnerabilities/windows_tips',views.windows,name='windows'),
    path('vulnerabilites/code_vul/path_hijack',views.path_hijack,name='path_hijack'),
    path('vulnerabilities/web_vul/file_magic_numbers',views.file_magick_numbers,name='file_magick_numbers'),
    path('vulnerabilities/web_vul/xee',views.xee,name='xee'),
    path('vulnerabilities/ad/esc4',views.esc4,name='esc4'),
    path('vulnerabilities/ad/esc9',views.esc9,name='esc9'),
    path('vulnerabilities/ad/ADCS',views.ADCS,name='ADCS'),
    path('vulnerabilities/ad/GPO',views.GPO,name='GPO'),

    path('tools', views.tools,name='tools'),
    path('tools/environment/docker',views.docker,name='docker'),
    path('tools/Analyzer/jd_gui',views.jd_gui,name='jd_gui'),
    path('tools/string_check', views.string_check,name='string_check'),
    path('tools/searchsploit',views.searchsploit,name='searchsploit'),
    path('tools/Cracker/hashcat',views.hashcat_view,name='hashcat'),
    path('tools/Cracker/hash-identifier',views.hash_identifier,name='hash_identifier'),
    path('tools/ssh',views.ssh,name='ssh'),
    path('tools/Enumeration/WPScan',views.wpscan,name = 'wpscan'),
    path('tools/Enumeration/Nikto',views.nikto,name='nikto'),
    path('tools/Enumeration/git',views.git,name='git'),
    path('tools/Enumeration/sqlmap',views.sqlmap,name='sqlmap'),
    path('tools/Enumeration/ltrace',views.ltrace,name='ltrace'),
    path('tools/Enumeration/nmap',views.nmap,name='nmap'),
    path('tools/remote_access/snmpwalk',views.snmpwalk,name='snmpwalk'),
    path('tools/Enumeration/ffuf',views.ffuf,name='ffuf'),
    path('tools/remote_access/socat',views.socat,name='socat'),
    path('tools/remote_access/chisel',views.chisel,name='chisel'),
    path('tools/request_handler',views.curl,name='curl'),
    path('tools/utils/xxd',views.xxd,name='xxd'),
    path('tools/remote_access/openssl',views.openssl,name='openssl'),
    path('tools/malicious_codes/php_webshell',views.php_webshell,name='php_webshell'),
    path('tools/utils/grep',views.grep,name='grep'),
    path('tools/binary_analysis/ps',views.ps,name='ps'),
    path('tools/binary_analysis/identify',views.identify,name='identify'),
    path('tools/binary_analysis/steghide',views.steghide,name='steghide'),
    path('tools/remote_access/scp',views.scp,name='scp'),
    path('tools/Enumeration/gobuster',views.gobuster,name='gobuster'),
    path('tools/Payload_generator',views.msfvenom,name='msfvenom'),
    path('tools/remote_access/nc64.exe',views.nc64_exe,name='nc64_exe',),
    path('tools/payload_generator',views.multi_handler,name='multi_handler'),
    path('tools/malicious_codes/sqli_codes',views.sqli_codes,name='sqli_codes'),
    path('tools/remote_access/snmp_brute',views.snmp_brute,name='snmp_brute'),
    path('tools/malicious_codes',views.postgres,name='postgres'),
    path('tools/cracker/john',views.john,name='john'),
    path('tools/remote_access/nc',views.nc,name='nc'),
    path('tools/container/lxd',views.lxd,name='lxd'),
    path('tools/malicious_codes/mysql',views.mysql,name='mysql'),
    path('tools/cracker/hydra',views.hydra,name='hydra'),
    path('tools/enumeration/cewl',views.cewl,name='cewl'),
    path('tools/utils/chown',views.chown,name='chown'),
    path('tools/payload_generator/gcc',views.gcc,name='gcc'),
    path('tools/remote_access/ftp',views.ftp,name='ftp'),
    path('tools/analyzer/mdb',views.mdb,name='mdb'),
    path('tools/analyzer/7z',views.seven_zip,name='7z'),
    path('tools/windows_cmds',views.windows_cmd,name='windows_cmd'),
    path('tools/windows/potato_family',views.potato_family,name='potato_family'),
    path('tools/enumeration/enum4linux',views.enum4linux,name='enum4linux'),
    path('tools/Privilege_collection',views.AD_priv,name='priv_collection'),
    path('tools/CMS_RevShell',views.cms_revshell,name='cms_revshell'),
    path('tools/LFI_location',views.LFI,name='lfi'),
    path('tools/Analyzer/kpcli',views.kpcli,name='kpcli'),
    path('tools/Enumeration/nfs',views.nfs,name='nfs'),
    path('tools/Cracker/gpp-decrypt',views.gpp_decrypt,name='gpp_decrypt'),
    path('tools/utils/iconv',views.iconv,name='iconv'),
    path('tools/Enumeration/username-anarchy',views.username_anarchy,name='username_anarchy'),
    path('tools/malicious_codes/mssql',views.mssql,name='mssql'),
    path('tools/Enumeration/windows-exploit-suggester',views.windows_exploit_suggester,name='windows-exploit-suggester'),
    path('tools/Cracker/pwsafe',views.pwsafe,name='pwsafe'),
    path('tools/Cracker/keepassxc-cli',views.keepassxc_cli,name='keepassxc-cli'),
    path('tools/payload_generator/javac',views.javac,name='javac'),
    path('tools/Cracker/firefox_decrypt',views.firefox_decrypt,name='firefox_decrypt'),
    path('tools/utils/awk',views.awk,name='awk'),
    path('tools/Enumeration/dirsearch',views.dirsearch,name='dirsearch'),
    path('tools/utils/md5sum',views.md5sum,name='md5sum'),
    path('tools/remote_access/xfreerdp3',views.xfreerdp3,name='xfreerdp3'),
    path('tools/utils/clipboard_problem',views.clipboard,name='clipboard'),
    path('tools/utils/base64',views.base64,name='base64'),
    path('tools/remote_access/smbget',views.smbget,name='smbget'),
    path('tools/remote_access/smdb',views.smdb,name='smdb'),
    path('tools/utils/docx2txt',views.docx2txt,name='docx2txt'),
    path('tools/utils/packet_loss',views.packet_loss,name='packet_loss'),
    path('tools/malicious_codes/java_jdb',views.java_jdb,name='java_jdb'),
    path('tools/request_handler/wireshark',views.wireshark,name='wireshark'),
    path('tools/binary_analysis/exiftool',views.exiftool,name='exiftool'),
    path('tools/utils/burpsuite',views.burpsuite,name='burpsuite'),


    path('tools/windows/nxc',views.nxc,name='nxc'),
    path('tools/windows/certipy',views.certipy,name='certipy'),
    path('tools/windows/impacket_changepasswd',views.impacket_changepasswd,name='impacket_changepasswd'),
    path('tools/windows/evil_winrm',views.evil_winrm,name='evil_winrm'),
    path('tools/windows/smbclient',views.smbclient,name='smbclient'),
    path('tools/windows/crackmapexec',views.crackmapexec,name='crackmapexec'),
    path('tools/windows/impacket_smbserver',views.impacket_smbserver,name='impacket_smbserver'),
    path('tools/windows/commands',views.command,name='command'),
    path('tools/windows/PowerUp_ps1',views.powerup,name='powerup'),
    path('tools/windows/impacket_psexec',views.impacket_psexec,name='impacket_psexec'),
    path('tools/windows/PowerView',views.PowerView,name='powerview'),
    path('tools/windows/sc_exe',views.sc_exe,name='sc_exe'),
    path('tools/windows/impacket-lookupsid',views.impacket_lookupsid,name='impacket_lookupsid'),
    path('tools/windows/impacket_secretsdump',views.impacket_secretsdump,name='impacket_secretsdump'),
    path('tools/windows/smbmap',views.smbmap,name='smbmap'),
    path('tools/windwos/impacket-GetADUsers',views.impacket_getadusers,name='impacket-getadusers'),
    path('tools/windows/impacket-GetUserSPNs',views.impacket_getuserrspns,name='impacket-getuserspns'),
    path('tools/windows/ldapsearch',views.ldapsearch,name='ldapsearch'),
    path('tools/windows/procdump',views.procdump,name='procdump'),
    path('tools/wimdows/impacket-mssqlclient',views.impacket_mssqlclient,name='impacket-mssqlclient'),
    path('tools/windows/responder',views.responder,name='responder'),
    path('tools/windows/certify.exe',views.certify_exe,name='certify_exe'),
    path('tools/windows/rubeus.exe',views.rubeus,name='rubeus'),
    path('tools/windows/certipy_ad',views.certipy_ad,name='certipy_ad'),
    path('tools/windows/impacket-getNPUsers',views.impacket_getupusers,name='impacket-getnpusers'),
    path('tools/windows/PrintSpoofer',views.print_spoofer,name='printspoofer'),
    path('tools/windows/targetedKerberoast',views.targetedKerberoast,name='targetedKerberoast'),
    path('tools/windows/bloodyAD',views.bloodyAD,name='bloodyAD'),
    path('tools/windows/impacket-dpapi',views.impacket_dpapi,name='impacket-dpapi'),
    path('tools/windows/mimikatz.exe',views.mimikatz,name='mimikatz'),
    path('tools/windows/SharpGPOAbuse.exe',views.shrapgpoabuse,name='sharpgpoabuse'),
    path('tools/windows/remmina',views.remmina,name='remmina'),
    path('tools/windows/pypykatz',views.pypykatz,name='pypykatz'),
    path('tools/windows/impacket_ntlmrelayx',views.impacket_ntlmrelayx,name='impacket_ntlmrelayx'),
    path('tools/windows/ntlm_theft',views.ntlm_theft,name='ntlm_theft'),
    path('tools/windows/RunasCS',views.RunasCS,name='RunasCS'),
    path('tools/windows/impacket_ticketer',views.impacket_ticketer,name='impacket_ticketer'),


    path('tools/AD/SharpHound',views.sharphound,name='sharphound'),
    path('tools/AD/net',views.net,name='net'),
    path('tools/AD/bloodhound-python',views.bloodhound_python,name='bloodhound-python'),
    path('tools/AD/pivoting',views.pivot,name='pivot'),
    path('tools/AD/linux_with_kerberos',views.linux_with_kerberos,name='linux_with_kerberos'),
    path('tools/AD/fishing_instruction',views.fishing_instruction,name='fishing_instruction'),
    path('tools/AD/ligolo-ng',views.ligolo_ng,name='ligolo_ng'),
    path('tools/AD/virtual_computer_accounts',views.virtual_computer_accounts,name='virtual_computer_accounts'),
    path('tools/AD/golden_ticket',views.golden_ticket,name='golden_ticket'),


    path('machines/', views.machines, name='machines'),
    path('machines/topology/', views.topology,name='Topology'),
    path('machines/armageddon/', views.armageddon,name='Armageddon'),
    path('machines/editorial',views.editorial,name='editorial'),
    path('machines/horizontal',views.horizontal,name='horizontal'),
    path('machines/blocky',views.blocky,name='blocky'),
    path('machines/down',views.down,name='down'),
    path('machines/titanic',views.titanic,name='titanic'),
    path('machines/perfection',views.perfection,name='perfection'),
    path('machines/data',views.data,name='data'),
    path('machines/CodePartTwo',views.codePartTwo,name='CodePartTwo'),
    path('machines/UpDown',views.updown,name='updown'),
    path('machines/soccer',views.soccer,name='soccer'),
    path('machines/usage',views.usage,name='usage'),
    path('machines/builder',views.builder,name='builder'),
    path('machines/networked',views.networked,name='networked'),
    path('machines/pandora',views.pandora,name='pandora'),
    path('machines/magick',views.magick,name='magick'),
    path('machines/nibbles',views.nibbles,name='nibbles'),
    path('machines/devoops',views.devoops,name='devoops'),
    path('machines/valentine',views.valentine,name='valentine'),
    path('machines/pilgrimage',views.pilgrimage,name='pilgrimage'),
    path('machines/irked',views.irked,name='irked'),
    path('machines/help',views.help,name='help'),
    path('machines/sea',views.sea,name='sea'),
    path('machines/openadmin',views.openadmin,name='openadmin'),
    path('machines/jarvis',views.jarvis,name='jarvis'),
    path('machines/mentor',views.mentor,name='mentor'),
    path('machines/tabby',views.tabby,name='tabby'),

    path('machines/windows/blue',views.blue,name='blue'),
    path('machines/windows/retro',views.retro,name='retro'),
    path('machines/windows/jerry',views.jerry,name='jerry'),
    path('machines/windows/buff',views.buff,name='buff'),
    path('machines/windows/love',views.love,name='love'),
    path('machines/windows/netmon',views.netmon,name='netmon'),
    path('machines/windows/chatterbox',views.chatterbox,name='chatterbox'),
    path('machines/windows/mailing',views.mailing,name='mailing'),
    path('machines/windows/access',views.access,name='access'),
    path('machines/windows/bounty',views.bounty,name='bounty'),
    path('machines/windows/jeeves',views.jeeves,name='jeeves'),
    path('machines/windows/remote',views.remote,name='remote'),
    path('machines/windows/heist',views.heist,name='heist'),
    path('machines/windows/secnotes',views.secnotes,name='secnotes'),
    path('machines/windows/querier',views.querier,name='querier'),
    path('machines/windows/arctic',views.arctic,name='arctic'),
    path('machines/windows/giddy',views.giddy,name='giddy'),
    path('machines/windows/sniper',views.sniper,name='sniper'),



    path('machines/AD/return',views.AD_return,name='return'),
    path('machines/AD/cicada',views.cicada,name='cicada'),
    path('machines/AD/active',views.active,name='active'),
    path('machines/AD/timelapse',views.timelapse,name='timelapse'),
    path('machines/AD/escape',views.escape,name='escape'),
    path('machines/AD/sauna',views.sauna,name='sauna'),
    path('machines/AD/forest',views.forest,name='forest'),
    path('machines/AD/monteverde',views.monteverde,name='monteverde'),
    path('machines/AD/administrator',views.administrator,name='administrator'),
    path('machines/AD/escapeTwo',views.escape2,name='escape2'),
    path('machines/AD/certified',views.certified,name='certified'),
    path('machines/AD/puppy',views.puppy,name='puppy'),
    path('machines/AD/thefrizz',views.thefrizz,name='thefrizz'),
    path('machines/AD/blackfield',views.blackfield,name='blackfield'),
    path('machines/AD/flight',views.flight,name='flight'),


    path('machines/PG_Play/amaterasu',views.amaterasu,name='amaterasu'),
    path('machines/PG_Play/potato',views.potato,name='potato'),
    path('machines/PG_Play/bsscute',views.bsscute,name='bsscute'),
    path('machines/PG_Play/blogger',views.blogger,name='blogger'),
    path('machines/PG_Play/funboxeasyenum',views.funboxeasyenum,name='funboxeasyenum'),
    path('machines/PG_Play/loly',views.loly,name='loly'),
    path('machines/PG_Play/stapler',views.stapler,name='stapler'),
    path('machines/PG_Play/gaara',views.gaara,name='gaara'),
    path('machines/PG_Play/glasgowsmile',views.glasgowsmile,name='glasgowsmile'),
    path('machines/PG_Play/vegeta1',views.veteta1,name='vegeta1'),
    path('machines/PG_Play/monitoring',views.monitoring,name='monitoring'),
    path('machines/PG_Play/katana',views.katana,name='katana'),
    path('machines/PG_Play/driftingblue',views.driftingblue,name='driftingblue'),
    path('machines/PG_Play/seppuku',views.seppuku,name='seppuku'),
    path('machines/PG_Play/election1',views.election1,name='election1'),
    path('machines/PG_Play/sosimple',views.sosimple,name='sosimple'),
    path('machines/PG_Play/BTRSys2_1',views.BTRSys2_1,name='BTRSys2_1'),
    path('machines/PG_Play/tre',views.tre,name='tre'),
    path('machines/PG_Play/DC_9',views.dc_9,name='dc_9'),
    path('machines/PG_Play/insanityhosting',views.insanityhosting,name='insanityhosting'),

    path('machines/PG_Practice/ClamAV',views.ClamAV,name='ClamAV'),
    path('machines/PG_Practice/pelican',views.pelican,name='pelican'),
    path('machines/PG_Practice/payday',views.payday,name='payday'),
    path('machines/PG_Practice/snookums',views.snookums,name='snookums'),
    path('machines/PG_Practice/bratarina',views.bratarina,name='bratarina'),
    path('machines/PG_Practice/nibbles',views.pg_nibbles,name='pg_nibbles'),
    path('machines/PG_Practice/zenphoto',views.zenphoto,name='zenphoto'),
    path('machines/PG_Practice/hetemit',views.hetemit,name='hetemit'),

    path('machines/PG_Practice/kevin',views.kevin,name='kevin'),
    path('machines/PG_Practice/internal',views.internal,name='internal'),
    path('machines/PG_Practice/algenon',views.algenon,name='algenon'),


    path('machines/OffSec/secura',views.secura,name='secura'),
    path('mechines/OffSec/Medtech',views.medtech,name='medtech'),
    path('machines/OffSec/relia',views.relia_home,name='relia_home'),
    path('machines/OffSec/relia/box249',views.box249,name='box249'),
    path('machines/OffSec/relia/box248',views.box248,name='box248'),
    path('machines/OffSec/relia/box247',views.box247,name='box247'),
    path('machines/OffSec/relia/box246',views.box246,name='box246'),
    path('machines/OffSec/relia/box245',views.box245,name='box245'),
    path('machines/OffSec/relia/box191',views.box191,name='box191'),
    path('machines/OffSec/relia/box6',views.box6,name='box6'),
    path('machines/OffSec/relia/box7',views.box7,name='box7'),
    path('machines/OffSec/relia/box14',views.box14,name='box14'),
    path('machines/OffSec/relia/box15',views.box15,name='box15'),
    path('machines/OffSec/relia/box19',views.box19,name='box19'),
    path('machines/OffSec/relia/box20',views.box20,name='box20'),
    path('machines/OffSec/relia/box21',views.box21,name='box21'),
    path('machines/OffSec/relia/box30',views.box30,name='box30'),
    path('machines/OffSec/relia/box189',views.box189,name='box189'),
    path('machines/OffSec/relia/box250',views.box250,name='box250'),

    path('machines/OffSec/OSCPB/home',views.OSCP_B,name='oscp_b'),
    path('machines/OffSec/OSCPB/146',views.box146,name='box146'),
    path('machines/OffSec/OSCPB/147',views.box147,name='box147'),
    path('machines/OffSec/OSCPB/148',views.box148,name='box148'),
    path('machines/OffSec/OSCPB/149',views.box149,name='box149'),
    path('machines/OffSec/OSCPB/150',views.box150,name='box150'),
    path('machines/OffSec/OSCPB/151',views.box151,name='box151'),

    path('machines/OffSec/OSCPA/home',views.oscp_a,name='oscp_a'),
    path('machines/OffSec/OSCPA/box140',views.box140,name='box140'),
    path('machines/OffSec/OSCPA/box141',views.box141,name='box141'),
    path('machines/OffSec/OSCPA/box142',views.box142,name='box142'),
    path('machines/OffSec/OSCPA/box143',views.box143,name='box143'),
    path('machines/OffSec/OSCPA/box144',views.box144,name='box144'),
    path('machines/OffSec/OSCPA/box145',views.box145,name='box145'),

    path('machines/OffSec/laser',views.laser,name='laser'),
    path('machines/OffSec/poseidon',views.poseidon,name='poseidon'),




    path('Code-Analyze/PHP',views.laravel_source_code,name='laravel_source_code'),
    path("Code-Analyze/Exploit/Laravel",views.laravel_exploit_code,name='laravel_exploit'),
    path('Code-Analyze/Exploit/Strapi',views.strapi_exploit_code,name='strapi_exploit_code'),
    path('Code-Analyze/Exploit/Dirty-Socket',views.dirty_socket_code,name='dirty_socket_code'),
    path('Code-Analyze/Python/decrypt_py',views.decrypt_py,name='decrypt_py'),


    path('MITM/1',views.page_1,name='page_1'),
    path('LearnThrough/routing',views.routing,name='routing'),
    path('LearnThrough/routing/OSIModel',views.osiModel,name='OSIModel'),
    path('LearnThrough/routing/IP_Routing',views.ip_routing,name='IProuting'),



    path('tips',views.tips,name='tips'),
    path('tips/history/initial_access',views.initial_access,name='initial_access'),
    path('tips/history/lateral_movement',views.lateral_movement,name='lateral_movement'),
    path('tips/history/PrivEsc',views.PrivEsc,name='PrivEsc'),
    path('tips/file/file_extensions',views.file_extensions,name='file_extensions')
]